let button = document.querySelector('button');
let quoteDatabase = ["The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "The best way to predict the future is to create it. - Peter Drucker",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Whether you think you can or you think you can’t, you’re right. - Henry Ford",
    "I have learned over the years that when one’s mind is made up, this diminishes fear. - Rosa Parks",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "The best revenge is massive success. - Frank Sinatra",
    "Life is what happens when you’re busy making other plans. - John Lennon",
    "Dream big and dare to fail. - Norman Vaughan",
    "You may be disappointed if you fail, but you are doomed if you don’t try. - Beverly Sills",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "Don’t wait. The time will never be just right. - Napoleon Hill",
    "Act as if what you do makes a difference. It does. - William James",
    "The harder the conflict, the greater the triumph. - George Washington",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The best preparation for tomorrow is doing your best today. - H. Jackson Brown, Jr.",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The best way out is always through. - Robert Frost",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "The biggest risk is not taking any risk. - Mark Zuckerberg",
    "The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart",
    "Do one thing every day that scares you. - Eleanor Roosevelt",
    "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
    "What we think, we become. - Buddha",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
    "The greatest discovery of all time is that a person can change his future by merely changing his attitude. - Oprah Winfrey",
    "What you do speaks so loudly that I cannot hear what you say. - Ralph Waldo Emerson",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "Do not follow where the path may lead. Go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Your life does not get better by chance, it gets better by change. - Jim Rohn",
    "Act as if what you do makes a difference. It does. - William James",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "Dream big and dare to fail. - Norman Vaughan",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The best preparation for tomorrow is doing your best today. - H. Jackson Brown, Jr.",
    "Don’t wait. The time will never be just right. - Napoleon Hill",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "You may be disappointed if you fail, but you are doomed if you don’t try. - Beverly Sills",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "What we think, we become. - Buddha",
    "The best way out is always through. - Robert Frost",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "The biggest risk is not taking any risk. - Mark Zuckerberg",
    "The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart",
    "What you do speaks so loudly that I cannot hear what you say. - Ralph Waldo Emerson",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The best way to achieve your goals is to help others achieve theirs. - Unknown",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The harder the conflict, the greater the triumph. - George Washington",
    "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Do one thing every day that scares you. - Eleanor Roosevelt",
    "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
    "The greatest discovery of all time is that a person can change his future by merely changing his attitude. - Oprah Winfrey",
    "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "Your life does not get better by chance, it gets better by change. - Jim Rohn"
];
let generateQuote = () => {
    let randomIndex = Math.floor(Math.random() * quoteDatabase.length);
    let quote = quoteDatabase[randomIndex];
    let quoteBox = document.getElementById('quote');
    quoteBox.innerText = quote;
}

button.addEventListener('click', generateQuote);